# Generated by Django 4.1.5 on 2023-01-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados',
            options={'ordering': ['nome'], 'verbose_name': 'Cadastro de Cliente', 'verbose_name_plural': 'Cadastros de Clientes'},
        ),
        migrations.AddField(
            model_name='dados',
            name='aprovado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='dados',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='dados',
            name='observacoes',
            field=models.TextField(default=1, verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dados',
            name='email',
            field=models.EmailField(max_length=75, verbose_name='Email'),
        ),
    ]
